CREATE VIEW V_DIS_TRANSPORTORDER_FILTER AS
-- This is a copy of V_TA without the expensive columns
SELECT
	S1.SENDUNG_TIX AS TA_TIX,
	S1.SENDUNG_N AS TA_N,
	S1.FIX_KEY AS TA_FIX_KEY,
	S1.SENDUNGSART AS TA_ART,
	S1.FIRMA,
	S1.NIEDERLASSUNG AS NL,
	S1.U_VERSION,
	S1.U_TIME,
	S1.LEISTUNGSDATUM AS LST_D,
	S1.RELATION AS TA_REL,
	REG.REGION AS TA_REGION,
	S1.STATUS_FRB,
	S1.STATUS_ABF,
	S1.STATUS_DIS,
	S1.FAKTUR_FREIGABE AS FAKTUR_FRG,
	S1.TRAN_ART AS VK_ART,
	P.PERS_TIX AS UNT_TIX,
	P.PERS_N AS UNT_N,
	P.PERS_I AS UNT_I,
	P.NAME1 AS UNT_NAME1,
	P.NAME2 AS UNT_NAME2,
	P.NAME3 AS UNT_NAME3,
	P.MATCH AS UNT_MATCH,
	P.ADR_ART AS UNT_ADR_ART,
	P.STR AS UNT_STR,
	P.SITZ_LAND AS UNT_LAND,
	P.SITZ_PLZ AS UNT_PLZ,
	P.SITZ_ORT AS UNT_ORT,
	P.SITZ_BEZ AS UNT_BEZ,
	P.SITZ_ORT_TIX AS UNT_ORT_TIX,
	U.LKW_TIX,
	U.LKW_K,
	U.LKW_AMTL_K,
	U.LKW_PLOMBE_K,
	U.ANH_TIX,
	U.ANH_K,
	U.ANH_AMTL_K,
	U.ANH_PLOMBE_K,
	U.FAHRER_N,
	U.FAHRER_NAME,
	U.BEIFAH_N,
	U.BEIFAH_NAME,
	U.STELLPLATZ_C AS LKW_STELLPLATZ_C,
	U.GEW AS LKW_GEW,
	U.VERTRAUEN_B,
	U.MOBIL_TEL_N,
	U.MOBIL_TEL_N2,
	U.LKW_WB_K,
	U.LKW_WB_ID,
	U.ANH_WB_K,
	U.ANH_WB_ID
FROM
	SENDUNG S1
	LEFT JOIN RELATION REL ON S1.RELATION = REL.KZ_RELATION
	AND S1.FIRMA = REL.FIRMENNUMMER
	AND S1.NIEDERLASSUNG = REL.NIEDERLASSUNG
	LEFT JOIN REGION REG ON REL.REGION = REG.REGION
	AND REL.FIRMENNUMMER = REG.FIRMA
	AND REL.NIEDERLASSUNG = REG.NIEDERLASSUNG
	AND REG.VERKEHR_K = 'F'::BPCHAR
	LEFT JOIN SEN_FRK_UNT U ON U.SEN_TIX = S1.SENDUNG_TIX
	AND U.LFD_N = 1::NUMERIC
	LEFT JOIN V_PERS_NOREGION P ON U.UNT_TIX = P.TIX
WHERE
	S1.SENDUNGSART = ANY (ARRAY['S'::BPCHAR, 's'::BPCHAR])