Frontend -> "New Dispo Backend" : Request tour optimization (TA_TIX)
activate "New Dispo Backend"
"New Dispo Backend" -> "TMS Bridge" : Request transport order (via TA_TIX)
"TMS Bridge" -> "New Dispo Backend" : Return transport order
"New Dispo Backend" -> "New Dispo Backend" : Extract tour points
"New Dispo Backend" -> "New Dispo Backend" : Map tour points to xServer API DTO
"New Dispo Backend" -> xServer : Request tour order optimization
xServer -> "New Dispo Backend" : Return optimized tour order
"New Dispo Backend" -> "New Dispo Backend" : Map tour points to TMS DTO
"New Dispo Backend" -> "TMS Bridge" : Update tour points in transport order
"TMS Bridge" -> "New Dispo Backend" : Return updated transport order
note right of "TMS Bridge" : Maybe just the tour points?
"New Dispo Backend" -> Frontend : Return optimized tour point order
deactivate "New Dispo Backend"
activate Frontend
alt #LightGreen Tour point order hasn't changed
    Frontend -> Frontend : Do nothing
end
alt #Yellow Tour point order has changed
    Frontend -> Frontend : Render new tour point order\n(without temporal context)
end
deactivate Frontend

